[tool.poetry]
name = "selfgnn-main"
version = "0.1.0"
description = ""
authors = ["Adrian Racki"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.8"
torch-geometric = "^2.6.1"
torch = "^2.5.1"
numpy = "^2.2.0"
ipykernel = "^6.29.5"
rdkit = "^2024.3.6"
pandas = "^2.2.3"
matplotlib = "^3.9.3"
scikit-learn = "^1.6.0"
lightning = "^2.4.0"
mlflow = "^2.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
