optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0032
  weight_decay: 6.00e-05
scheduler:
  _target_: torch.optim.lr_scheduler.SequentialLR
  schedulers:
    - _target_: torch.optim.lr_scheduler.LinearLR
      start_factor: 0.1
      end_factor: 1.0
      total_iters: 2
    - _target_: torch.optim.lr_scheduler.CosineAnnealingLR
      T_max: 50
      eta_min: 1e-5
    - _target_: torch.optim.lr_scheduler.ConstantLR
      factor: 0.01
      total_iters: 10000
  milestones: [2, 52]
loss:
  _target_: losses.WeightedHuberLoss
  delta: 0.2
  weight_by_frq: true

model_k_params: 1 # number of parameters in the model in thousands

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 10
  max_epochs: 60
  accelerator: cpu
  log_every_n_steps: 400
  logger:
    _target_: lightning.pytorch.loggers.MLFlowLogger
    experiment_name: selfgnn
    run_name: ${run_name}
    tracking_uri: http://127.0.0.1:5001
    # mlflow server --host 127.0.0.1 --port 5001
