optimizer:
  _target_: torch.optim.AdamW
  lr: 0.05
  weight_decay: 0.001
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 5
  T_mult: 2
  eta_min: 1e-5

loss:
  _target_: torch.nn.MSELoss

model_k_params: 1 # number of parameters in the model in thousands

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 200
  max_epochs: 200
  accelerator: cpu
  logger: null
    # _target_: lightning.pytorch.loggers.litlogger.LitLogger
    # name: ${run_name}
    # teamspace: IDAC-experiments
    # log_model: false
