optimizer:
  _target_: torch.optim.AdamW
  lr: 0.004305249796906613
  weight_decay: 0.0001669926134035445
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 5
  T_mult: 2
  eta_min: 1e-5

loss:
  _target_: torch.nn.MSELoss

model_k_params: 1 # number of parameters in the model in thousands logged in mlflow

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 30
  max_epochs: 110
  accelerator: cpu
  log_every_n_steps: 4
  # logger:
  #   _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  #   experiment_name: Heat_10fold
  #   run_name: ${run_name}
  #   tracking_uri: http://127.0.0.1:5000
  #   save_dir: ./mlruns
  #   # mlflow ui --port 5000 --backend-store-uri file:./mlruns
  