optimizer:
  _target_: torch.optim.AdamW
  lr: 0.005539555649254803
  weight_decay: 0.0004896752704346914
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 5
  T_mult: 2
  eta_min: 1e-5


loss:
  _target_: torch.nn.MSELoss

model_k_params: 1 # number of parameters in the model in thousands logged in mlflow

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 50
  max_epochs: 300
  accelerator: cpu
  log_every_n_steps: 10
  logger:
    _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
    experiment_name: Final_calculations
    run_name: ${run_name}
    tracking_uri: http://127.0.0.1:5000
    save_dir: ./mlruns
    # mlflow ui --port 5000 --backend-store-uri file:./mlruns
  