r2score:
  _target_: torchmetrics.R2Score
mse:
  _target_: torchmetrics.MeanSquaredError
mae:
  _target_: torchmetrics.MeanAbsoluteError
pearson:
  _target_: torchmetrics.PearsonCorrCoef
mape:
  _target_: torchmetrics.MeanAbsolutePercentageError