early_stopper:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val_R2Score
  min_delta: 0.005
  patience: 50
  verbose: False
  mode: max
  strict: True
  check_finite: True
lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: step
  log_momentum: False
  log_weight_decay: False
best_metrics:
  _target_: utils.best_metrics_callback.BestMetricsCallback
  run_name: ${run_name}
model_summary:
  _target_: lightning.pytorch.callbacks.ModelSummary
