early_stopper:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val_R2Score
  min_delta: 0.01
  patience: 15
  verbose: False
  mode: max
  strict: True
  check_finite: True
lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: step
  log_momentum: False
  log_weight_decay: False
# model_summary:
#   _target_: lightning.pytorch.callbacks.ModelSummary
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val_R2Score
  mode: max
  save_top_k: 1
  dirpath: ./checkpoints
  filename: ${run_name}_best
# parity_plotter:
#   _target_: utils.parity_plot_callback.ParityPlotCallback
#   run_name: ${run_name}


