_target_: model.GATEncoder
emb_size: 8
hidden_dim: 32
num_heads: 4
node_size_of_dicts: ${data.dataset.node_features.sizes}
edge_size_of_dicts: ${data.dataset.edge_features.sizes}
num_layers: 3
dropout_rate: 0.3
use_global_features: False
beta: False
global_pool: 
  _target_: torch_geometric.nn.aggr.SoftmaxAggregation
  t: 2
  learn: True
projector:
  _target_: generic.Projector
  in_features: 1
  out_features: 1 # This is inferred inside the model
  dropout_rate: 0.3
