# THIS IS BASELINE MODEL CONFIGURATION
_target_: model.base.BaseModel
embedding_layer:
  _target_: model.embedding.GraphEmbeddingLayer
  node_feature_sizes: ${data.dataset.node_features.sizes}
  edge_feature_sizes: ${data.dataset.edge_features.sizes}
  global_features_module:
    _target_: torch.nn.Linear
    in_features: 15
    out_features: 15
  emb_size: 4
  global_features_size: 15
encoder_layer:
  _target_: model.gated_encoder.GatedEncoder
  _partial_: true
  hidden_dim: 32
  num_layers: 2
  n_experts: 3
  encoder_type: "GAT"
  num_heads: 1
  shared_expert: true
pooling_layer:
  _target_: model.pooling.IDACPooling
  _partial_: true
  num_mols: 3
  pooling_layer:
    _target_: torch_geometric.nn.aggr.MLPAggregation
    _partial_: true
    in_channels: 32
    out_channels: 32
    max_num_elements: 50
    num_layers: 1
projector_layer:
  _target_: model.idac_layers.IDACProjector
  _partial_: true
  out_features: 1
  dropout_rate: 0.3
  append_global_features: true
  global_features_size: 45  # num mols * num global features
