_target_: model.GraphModelWrapper
gating: false
experts:
  - _target_: model.GCNEncoder
    hidden_dim: 28
    num_layers: 2
    node_size_of_dicts: ${data.dataset.node_features.sizes}
    edge_size_of_dicts: ${data.dataset.edge_features.sizes}