_target_: model.base.BaseModel
embedding_layer:
  _target_: model.embedding.GraphEmbeddingLayer
  node_feature_sizes: ${data.dataset.node_features.sizes}
  edge_feature_sizes: ${data.dataset.edge_features.sizes}
  global_features_module:
    _target_: torch.nn.Linear
    in_features: 15
    out_features: 15
  emb_size: 4
  global_features_size: 15
encoder_layer:
  _target_: model.encoder.GINEncoder
  _partial_: true
  hidden_dim: 32
  num_layers: 2
  internal_model: "CrossNetV2"
  cross_layers: 1
pooling_layer:
  _target_: model.pooling.IDACTransformerPooling
  num_mols: 3
projector_layer:
  _target_: model.idac_layers.IDACTransformerProjector
  _partial_: true
  num_mols: 3
  d_model: 32
  nhead: 2
  num_transformer_layers: 2
  dim_feedforward: 32
  dropout_rate: 0.25
  out_features: 1
  append_global_features: false
  global_features_size: 45  # num_mols * num_global_features
