_target_: model.GraphModelWrapper
gating: true
experts:
  - _target_: model.GINEncoder
    hidden_dim: 16
    num_layers: 2
    internal_model: "CrossNetV2"
    cross_layers: 1
    node_size_of_dicts: ${data.dataset.node_features.sizes}
    edge_size_of_dicts: ${data.dataset.edge_features.sizes}
  - _target_: model.GINEncoder
    hidden_dim: 16
    num_layers: 2
    internal_model: "CrossNetV2"
    cross_layers: 1
    node_size_of_dicts: ${data.dataset.node_features.sizes}
    edge_size_of_dicts: ${data.dataset.edge_features.sizes}
  - _target_: model.GINEncoder
    hidden_dim: 16
    num_layers: 2
    internal_model: "CrossNetV2"
    cross_layers: 1
    node_size_of_dicts: ${data.dataset.node_features.sizes}
    edge_size_of_dicts: ${data.dataset.edge_features.sizes}
  - _target_: model.GINEncoder
    hidden_dim: 16
    num_layers: 2
    internal_model: "CrossNetV2"
    cross_layers: 1
    node_size_of_dicts: ${data.dataset.node_features.sizes}
    edge_size_of_dicts: ${data.dataset.edge_features.sizes}